<a href="https://colab.research.google.com/github/cabreratr/hacking-civico/blob/master/tareas/03-exploracion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p align="center">
<img src="http://codeandomexico.org/resources/img/codeandomexico.png" width="500" alt="Codeando M√©xico"><br>
<a href="http://www.codeandomexico.org/" target="_blank"><img src="https://img.shields.io/badge/website-CodeandoMexico-00D88E.svg"></a>
<a href="http://slack.codeandomexico.org/" target="_blank"><img src="https://img.shields.io/badge/slack-CodeandoMexico-EC0E4F.svg"></a>
</p>
<!-- __ -->

# Curso de Datos Abiertos y Hacking C√≠vico

Este curso tiene como objetivo habilitar las capacidades de la ciudadaniÃÅa y los servidores p√∫blicos en el uso y generaci√≥n de datos abiertos para el bien com√∫n. Puedes encontrar m√°s informaci√≥n [aqu√≠](https://github.com/CodeandoMexico/hacking-civico).

# Exploraci√≥n de datos: COVID-19 en M√©xico

En este cuaderno aprenderemos algunas bases de exploraci√≥n de datos. Los datos a utilizar son los datos abiertos sobre COVID-19 en M√©xico, los cuales pueden ser accedidos directamente desde el portal: https://www.gob.mx/salud/documentos/datos-abiertos-152127

Del portal de datos abiertos podemos encontrar dos enlaces, uno para descargar el conjunto de datos y otro para descargar el diccionario; as√≠ que podemos automatizar el proceso de descarga y descompresi√≥n de la informaci√≥n.

Para obtener los datos, s√≥lo basta que ejecutes la siguiente l√≠nea de c√≥digo, que contiene el comando de descarga de la informaci√≥n.

In [ ]:
# Para descargar el conjunto de datos
!wget http://datosabiertos.salud.gob.mx/gobmx/salud/datos_abiertos/datos_abiertos_covid19.zip

# Para descargar el diccionario de los datos
!wget http://datosabiertos.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip

# Descomprimimos ambas carpetas y movemos archivos
!unzip datos_abiertos_covid19.zip
!unzip diccionario_datos_covid19.zip
!mv ./diccionario_datos_covid19/*.xlsx .
!mv *COVID19MEXICO.csv COVID19MEXICO.csv

# Eliminamos las carpetas comprimidas
!rm -rf diccionario_datos_covid19
!rm datos_abiertos_covid19.zip
!rm diccionario_datos_covid19.zip

--2020-10-06 02:22:00--  http://datosabiertos.salud.gob.mx/gobmx/salud/datos_abiertos/datos_abiertos_covid19.zip
Resolving datosabiertos.salud.gob.mx (datosabiertos.salud.gob.mx)... 187.210.186.146
Connecting to datosabiertos.salud.gob.mx (datosabiertos.salud.gob.mx)|187.210.186.146|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 37469377 (36M) [application/x-zip-compressed]
Saving to: ‚Äòdatos_abiertos_covid19.zip‚Äô

datos_abiertos_covi 100%[===================>]  35.73M  9.49MB/s    in 4.7s

2020-10-06 02:22:05 (7.58 MB/s) - ‚Äòdatos_abiertos_covid19.zip‚Äô saved [37469377/37469377]

--2020-10-06 02:22:05--  http://datosabiertos.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip
Resolving datosabiertos.salud.gob.mx (datosabiertos.salud.gob.mx)... 187.210.186.146
Connecting to datosabiertos.salud.gob.mx (datosabiertos.salud.gob.mx)|187.210.186.146|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 81416 (80K) [application/x-zip-compressed]
Saving to: ‚Äòdiccionario_datos_covid19.zip‚Äô

diccionario_datos_c 100%[===================>]  79.51K   102KB/s    in 0.8s

2020-10-06 02:22:08 (102 KB/s) - ‚Äòdiccionario_datos_covid19.zip‚Äô saved [81416/81416]

Archive:  datos_abiertos_covid19.zip
  inflating: 201005COVID19MEXICO.csv
Archive:  diccionario_datos_covid19.zip
  inflating: diccionario_datos_covid19/Catalogos_0412.xlsx
  inflating: diccionario_datos_covid19/Descriptores_0419.xlsx

Hasta este punto, si abres la barra lateral izaquiera, deber√≠as ser capaz de encontrar los datos:

- `COVID19MEXICO.csv`
- `Catalogos_0412.xlsx`
- `Descriptores_0419.xlsx`

üëàüèº

## Carga

Ahora que tenemos los datos, procederemos a cargarlos. Para cargar los datos, primero importaremos algunos paquetes de Python, pues su funcionalidad nos ser√° muy util.

In [5]:
import statistics

import pandas as pd
import numpy as np

In [6]:
# Especificamos el nombre del archivo por abrir
nombre_archivo = 'COVID19MEXICO.csv'

# Utilizamos la funci√≥n de Pandas para cargar un archivo CSV
data = pd.read_csv(nombre_archivo, encoding='latin-1')

Mostramos la cabeza (primeros elementos del archivo).

In [ ]:
data.head()

  FECHA_ACTUALIZACION ID_REGISTRO  ORIGEN  ...  PAIS_NACIONALIDAD  PAIS_ORIGEN  UCI
0          2020-09-03      097d14       2  ...            M√É¬©xico           99   97
1          2020-09-03      1b7adb       2  ...            M√É¬©xico           99    2
2          2020-09-03      11daaa       2  ...            M√É¬©xico           99   97
3          2020-09-03      17c9eb       2  ...            M√É¬©xico           99   97
4          2020-09-03      14f12c       2  ...            M√É¬©xico           99   97

[5 rows x 35 columns]

Ahora procedemos a cargar el archivo con los descriptores.

In [7]:
nombre_diccionario = 'Descriptores_0419.xlsx'
diccionario = pd.read_excel(nombre_diccionario)

In [ ]:
diccionario

    N¬∫  ...                                   FORMATO O FUENTE
0    1  ...                                         AAAA-MM-DD
1    2  ...                                             TEXTO
2    3  ...  CAT√ÅLOGO: ORIGEN                              ...
3    4  ...  CAT√ÅLOGO: SECTOR                              ...
4    5  ...                                CATAL√ìGO: ENTIDADES
5    6  ...       CAT√ÅLOGO: SEXO
6    7  ...                                CATAL√ìGO: ENTIDADES
7    8  ...                                CATAL√ìGO: ENTIDADES
8    9  ...                               CATAL√ìGO: MUNICIPIOS
9   10  ...                           CAT√ÅLOGO: TIPO_PACIENTE
10  11  ...                                         AAAA-MM-DD
11  12  ...                                         AAAA-MM-DD
12  13  ...                                         AAAA-MM-DD
13  14  ...  CAT√ÅLOGO: SI_ NO                              ...
14  15  ...  CAT√ÅLOGO: SI_ NO                              ...
15  16  ...                                   N√öMERICA EN A√ëOS
16  17  ...                            CAT√ÅLOGO: NACIONALIDAD
17  18  ...  CAT√ÅLOGO: SI_ NO                              ...
18  19  ...  CAT√ÅLOGO: SI_ NO                              ...
19  20  ...  CAT√ÅLOGO: SI_ NO                              ...
20  21  ...  CAT√ÅLOGO: SI_ NO                              ...
21  22  ...  CAT√ÅLOGO: SI_ NO                              ...
22  23  ...  CAT√ÅLOGO: SI_ NO                              ...
23  24  ...  CAT√ÅLOGO: SI_ NO                              ...
24  25  ...  CAT√ÅLOGO: SI_ NO                              ...
25  26  ...  CAT√ÅLOGO: SI_ NO                              ...
26  27  ...  CAT√ÅLOGO: SI_ NO                              ...
27  28  ...  CAT√ÅLOGO: SI_ NO                              ...
28  29  ...  CAT√ÅLOGO: SI_ NO                              ...
29  30  ...  CAT√ÅLOGO: SI_ NO                              ...
30  31  ...                                CAT√ÅLOGO: RESULTADO
31  32  ...  CAT√ÅLOGO: SI_ NO                              ...
32  33  ...                               TEXTO, 99= SE IGNORA
33  34  ...                               TEXTO, 97= NO APLICA
34  35  ...  CAT√ÅLOGO: SI_ NO                              ...

[35 rows x 4 columns]

Finalmente, cargamos el rachivo de cat√°logos.

In [8]:
nombre_cat = 'Catalogos_0412.xlsx'
sheets = ['ORIGEN', 'SECTOR', 'SEXO', 'TIPO_PACIENTE', 'SI_NO', 'NACIONALIDAD', 'RESULTADO', 'de ENTIDADES', 'MUNICIPIOS']
catalogues = {}
for sheet in sheets:
  catalogue = pd.read_excel(nombre_cat, sheet_name='Cat√°logo ' + sheet)
  catalogue.columns = catalogue.columns.str.replace(' ', '_')
  catalogue.columns = catalogue.columns.str.replace('.', '')
  catalogue.columns = catalogue.columns.str.lower()
  new_catalogue = {sheet: catalogue}
  catalogues.update(new_catalogue)

In [9]:
catalogues

{'MUNICIPIOS':       clave_municipio        municipio  clave_entidad
 0                   1   AGUASCALIENTES              1
 1                   2         ASIENTOS              1
 2                   3         CALVILLO              1
 3                   4            COS√çO              1
 4                   5      JES√öS MAR√çA              1
 ...               ...              ...            ...
 2496              999  NO ESPECIFICADO             32
 2497              999  NO ESPECIFICADO             36
 2498              997        NO APLICA             97
 2499              998        SE IGNORA             98
 2500              999  NO ESPECIFICADO             99

 [2501 rows x 3 columns], 'NACIONALIDAD':    clave      descripci√≥n
 0      1         MEXICANA
 1      2       EXTRANJERA
 2     99  NO ESPECIFICADO, 'ORIGEN':    clave      descripci√≥n
 0      1            USMER
 1      2   FUERA DE USMER
 2     99  NO ESPECIFICADO, 'RESULTADO':   unnamed:_0              unnamed:_1
 0      CLAVE             DESCRIPCI√ìN
 1          1     Positivo SARS-CoV-2
 2          2  No positivo SARS-CoV-2
 3          3     Resultado pendiente, 'SECTOR':     clave      descripci√≥n
 0       1        CRUZ ROJA
 1       2              DIF
 2       3          ESTATAL
 3       4             IMSS
 4       5   IMSS-BIENESTAR
 5       6           ISSSTE
 6       7        MUNICIPAL
 7       8            PEMEX
 8       9          PRIVADA
 9      10           SEDENA
 10     11            SEMAR
 11     12              SSA
 12     13    UNIVERSITARIO
 13     99  NO ESPECIFICADO, 'SEXO':    clave      descripci√≥n
 0      1            MUJER
 1      2           HOMBRE
 2     99  NO ESPECIFICADO, 'SI_NO':    clave      descripci√≥n
 0      1              SI
 1      2              NO
 2     97        NO APLICA
 3     98        SE IGNORA
 4     99  NO ESPECIFICADO, 'TIPO_PACIENTE':    clave      descripci√≥n
 0      1      AMBULATORIO
 1      2    HOSPITALIZADO
 2     99  NO ESPECIFICADO, 'de ENTIDADES':     clave_entidad               entidad_federativa abreviatura
 0               1                   AGUASCALIENTES          AS
 1               2                  BAJA CALIFORNIA          BC
 2               3              BAJA CALIFORNIA SUR          BS
 3               4                         CAMPECHE          CC
 4               5             COAHUILA DE ZARAGOZA          CL
 5               6                           COLIMA          CM
 6               7                          CHIAPAS          CS
 7               8                        CHIHUAHUA          CH
 8               9                 CIUDAD DE M√âXICO          DF
 9              10                          DURANGO          DG
 10             11                       GUANAJUATO          GT
 11             12                         GUERRERO          GR
 12             13                          HIDALGO          HG
 13             14                          JALISCO          JC
 14             15                           M√âXICO          MC
 15             16              MICHOAC√ÅN DE OCAMPO          MN
 16             17                          MORELOS          MS
 17             18                          NAYARIT          NT
 18             19                       NUEVO LE√ìN          NL
 19             20                           OAXACA          OC
 20             21                           PUEBLA          PL
 21             22                        QUER√âTARO          QT
 22             23                     QUINTANA ROO          QR
 23             24                  SAN LUIS POTOS√ç          SP
 24             25                          SINALOA          SL
 25             26                           SONORA          SR
 26             27                          TABASCO          TC
 27             28                       TAMAULIPAS          TS
 28             29                         TLAXCALA          TL
 29             30  VERACRUZ DE IGNACIO DE LA LLAVE          VZ
 30             31                          YUCAT√ÅN          YN
 31             32                        ZACATECAS          ZS
 32             36         ESTADOS UNIDOS MEXICANOS         EUM
 33             97                        NO APLICA         NaN
 34             98                        SE IGNORA          SI
 35             99                  NO ESPECIFICADO          NE}

In [10]:
catalogues['SEXO']

   clave      descripci√≥n
0      1            MUJER
1      2           HOMBRE
2     99  NO ESPECIFICADO

##Perfilamiento

###Descripci√≥n General

In [11]:
# dimensi√≥n de los datos
print('N√∫mero de filas: {}'.format(data.shape[0]))
print('N√∫mero de columnas: {}'.format(data.shape[1]))

N√∫mero de filas: 1758582
N√∫mero de columnas: 35

In [12]:
# columnas (variables)
data.columns

Index(['FECHA_ACTUALIZACION', 'ID_REGISTRO', 'ORIGEN', 'SECTOR', 'ENTIDAD_UM',
       'SEXO', 'ENTIDAD_NAC', 'ENTIDAD_RES', 'MUNICIPIO_RES', 'TIPO_PACIENTE',
       'FECHA_INGRESO', 'FECHA_SINTOMAS', 'FECHA_DEF', 'INTUBADO', 'NEUMONIA',
       'EDAD', 'NACIONALIDAD', 'EMBARAZO', 'HABLA_LENGUA_INDIG', 'DIABETES',
       'EPOC', 'ASMA', 'INMUSUPR', 'HIPERTENSION', 'OTRA_COM',
       'CARDIOVASCULAR', 'OBESIDAD', 'RENAL_CRONICA', 'TABAQUISMO',
       'OTRO_CASO', 'RESULTADO', 'MIGRANTE', 'PAIS_NACIONALIDAD',
       'PAIS_ORIGEN', 'UCI'],
      dtype='object')

In [13]:
# limpieza del nombre de las columnas, remover espacios, car√°cteres especiales y pasar a min√∫sculas
data.columns = data.columns.str.replace(' ', '_')
data.columns = data.columns.str.replace('.', '')
data.columns = data.columns.str.lower()

In [14]:
# calcular n√∫mero de valores nulos por columna
for col in data.columns:
  print('Valores nulos en "{}": {}'.format(col,data[col].isna().sum()))

Valores nulos en "fecha_actualizacion": 0
Valores nulos en "id_registro": 0
Valores nulos en "origen": 0
Valores nulos en "sector": 0
Valores nulos en "entidad_um": 0
Valores nulos en "sexo": 0
Valores nulos en "entidad_nac": 0
Valores nulos en "entidad_res": 0
Valores nulos en "municipio_res": 0
Valores nulos en "tipo_paciente": 0
Valores nulos en "fecha_ingreso": 0
Valores nulos en "fecha_sintomas": 0
Valores nulos en "fecha_def": 0
Valores nulos en "intubado": 0
Valores nulos en "neumonia": 0
Valores nulos en "edad": 0
Valores nulos en "nacionalidad": 0
Valores nulos en "embarazo": 0
Valores nulos en "habla_lengua_indig": 0
Valores nulos en "diabetes": 0
Valores nulos en "epoc": 0
Valores nulos en "asma": 0
Valores nulos en "inmusupr": 0
Valores nulos en "hipertension": 0
Valores nulos en "otra_com": 0
Valores nulos en "cardiovascular": 0
Valores nulos en "obesidad": 0
Valores nulos en "renal_cronica": 0
Valores nulos en "tabaquismo": 0
Valores nulos en "otro_caso": 0
Valores nulos en "resultado": 0
Valores nulos en "migrante": 0
Valores nulos en "pais_nacionalidad": 0
Valores nulos en "pais_origen": 0
Valores nulos en "uci": 0

In [15]:
# tipos de datos
data.dtypes

fecha_actualizacion    object
id_registro            object
origen                  int64
sector                  int64
entidad_um              int64
sexo                    int64
entidad_nac             int64
entidad_res             int64
municipio_res           int64
tipo_paciente           int64
fecha_ingreso          object
fecha_sintomas         object
fecha_def              object
intubado                int64
neumonia                int64
edad                    int64
nacionalidad            int64
embarazo                int64
habla_lengua_indig      int64
diabetes                int64
epoc                    int64
asma                    int64
inmusupr                int64
hipertension            int64
otra_com                int64
cardiovascular          int64
obesidad                int64
renal_cronica           int64
tabaquismo              int64
otro_caso               int64
resultado               int64
migrante                int64
pais_nacionalidad      object
pais_origen            object
uci                     int64
dtype: object

###Limpieza

In [16]:
# convertimos a fecha algunas columnas
def cast_datetime_cols(df):
    timestamp_cols = [col for col in df.columns if "fecha" in col]
    df[timestamp_cols] = df[timestamp_cols].apply(lambda date_col: pd.to_datetime(date_col, errors="coerce"), axis=0)
    return df

data = cast_datetime_cols(data)

In [17]:
data.head()

  fecha_actualizacion id_registro  origen  ...  pais_nacionalidad  pais_origen  uci
0          2020-10-05      1c4b18       1  ...            M√É¬©xico           99    2
1          2020-10-05      081838       2  ...            M√É¬©xico           99   97
2          2020-10-05      0fefb1       2  ...            M√É¬©xico           99   97
3          2020-10-05      11ed05       2  ...            M√É¬©xico           99    1
4          2020-10-05      0ef3ff       1  ...            M√É¬©xico           99   97

[5 rows x 35 columns]

In [18]:
# unimos los datos con los catalogos para tener mejor entendimiento de ellos
data = (
    # unimos con el cat√°logo MUNICIPIOS y ENTIDADES
    data.merge(catalogues['de ENTIDADES'], how='left', left_on='entidad_res', right_on='clave_entidad').
    drop(columns=['entidad_res', 'abreviatura']).
    rename(columns={'entidad_federativa':'entidad_res'}).
    merge(catalogues['MUNICIPIOS'], how='left', left_on=['clave_entidad','municipio_res'], right_on=['clave_entidad','clave_municipio']).
    drop(columns=['municipio_res', 'clave_entidad', 'clave_municipio']).
    rename(columns={'municipio':'municipio_res'})
)

In [19]:
# unimos con el cat√°logo de ENTIDADES
entidades_cols = [col for col in data.columns if "entidad" in col and col != 'entidad_res']
for col in entidades_cols:
    data = (
        data.merge(catalogues['de ENTIDADES'], how='left', left_on=col, right_on='clave_entidad').
        drop(columns=[col, 'abreviatura', 'clave_entidad']).
        rename(columns={'entidad_federativa':col})
    )

In [20]:
# unimos con el cat√°logo SI_NO
sino_cols = ['intubado', 'neumonia', 'embarazo', 'habla_lengua_indig', 'diabetes', 'epoc', 'asma', 'inmusupr',
             'hipertension', 'otra_com', 'cardiovascular', 'obesidad', 'renal_cronica', 'tabaquismo', 
             'otro_caso', 'migrante', 'uci']
for col in sino_cols:
    data = (
        data.merge(catalogues['SI_NO'], how='left', left_on=col, right_on='clave').
        drop(columns=[col, 'clave']).
        rename(columns={'descripci√≥n':col})
    )

> **Nota:**
>
> Si ejecutaste una versi√≥n previa del cuaderno, notar√°s que en la siguiente secci√≥n aparec√≠a un error. A continuaci√≥n dejamos como un peque√±o par√©ntesis un poco m√°s de limpieza sobre el cuaderno.

1. Corregimos el nombre de las columnas:

In [21]:
catalogues['RESULTADO'].columns

Index(['unnamed:_0', 'unnamed:_1'], dtype='object')

In [22]:
catalogues['RESULTADO'].columns = ['clave', 'descripci√≥n']
catalogues['RESULTADO'].columns

Index(['clave', 'descripci√≥n'], dtype='object')

2. Removemos la (primera) fila que no nos es √∫til.

In [23]:
catalogues['RESULTADO'] = catalogues['RESULTADO'].drop(index=0)

3. Convertimos el tipo de dato.

In [24]:
catalogues['RESULTADO']['clave'] = catalogues['RESULTADO']['clave'].astype(int)

> Fin del par√©ntesis. Hasta esta secci√≥n, esta parte de limpieza permite continuar con el proceso de manera normal.

In [25]:
# unimos otras columnnas que comparten l√≥gica
other_cols = ['origen', 'sector', 'sexo', 'tipo_paciente', 'nacionalidad', 'resultado']
for col, cat in zip(other_cols, [x.upper() for x in other_cols]):
    data = (
        data.merge(catalogues[cat], how='left', left_on=col, right_on='clave').
        drop(columns=[col, 'clave']).
        rename(columns={'descripci√≥n':col})
    )

In [26]:
# creamos algunas variables que podr√≠an ser √∫tiles despu√©s
data['defuncion'] = ~data.fecha_def.isna()
data['mes_def'] = data.fecha_def.dt.month
data['a√±o_def'] = data.fecha_def.dt.year
data['mes_ingreso'] = data.fecha_ingreso.dt.month
data['a√±o_ingreso'] = data.fecha_ingreso.dt.year

In [27]:
data.head()

  fecha_actualizacion id_registro  ... mes_ingreso a√±o_ingreso
0          2020-10-05      1c4b18  ...           4        2020
1          2020-10-05      081838  ...           4        2020
2          2020-10-05      0fefb1  ...           5        2020
3          2020-10-05      11ed05  ...           5        2020
4          2020-10-05      0ef3ff  ...           5        2020

[5 rows x 40 columns]

###Filtros

**Distintas formas de filtrar lo mismo**

In [28]:
# usando query
data.query('nacionalidad == "MEXICANA"').head(2)

  fecha_actualizacion id_registro  ... mes_ingreso a√±o_ingreso
0          2020-10-05      1c4b18  ...           4        2020
1          2020-10-05      081838  ...           4        2020

[2 rows x 40 columns]

In [29]:
# haciendo referencia a la columna como √≠ndice
data[data['nacionalidad'] == 'MEXICANA'].head(2)

  fecha_actualizacion id_registro  ... mes_ingreso a√±o_ingreso
0          2020-10-05      1c4b18  ...           4        2020
1          2020-10-05      081838  ...           4        2020

[2 rows x 40 columns]

In [30]:
# seleccionando directamente la columna que queremos filtrar
data[data.nacionalidad == 'MEXICANA'].head(2)

  fecha_actualizacion id_registro  ... mes_ingreso a√±o_ingreso
0          2020-10-05      1c4b18  ...           4        2020
1          2020-10-05      081838  ...           4        2020

[2 rows x 40 columns]

**Filtrado m√∫ltiple**

In [31]:
# usando query podemos poner en el string del query todas las condiciones que queramos
data.query('nacionalidad == "MEXICANA" & entidad_res == "CIUDAD DE M√âXICO"').head(2)

  fecha_actualizacion id_registro  ... mes_ingreso a√±o_ingreso
0          2020-10-05      1c4b18  ...           4        2020
1          2020-10-05      081838  ...           4        2020

[2 rows x 40 columns]

In [32]:
# usando el filtrado tradicional debemos encerrar en par√©ntesis cada condici√≥n que queremos que cumpla nuestro filtro
data[(data['nacionalidad'] == "MEXICANA") & (data.entidad_res == "CIUDAD DE M√âXICO")].head(2)

  fecha_actualizacion id_registro  ... mes_ingreso a√±o_ingreso
0          2020-10-05      1c4b18  ...           4        2020
1          2020-10-05      081838  ...           4        2020

[2 rows x 40 columns]

###Res√∫menes

In [33]:
# una columna, una m√©trica
data.groupby('sexo').edad.mean()

sexo
HOMBRE    42.388726
MUJER     41.450503
Name: edad, dtype: float64

In [34]:
# una columna, varias m√©tricas
data.groupby('sexo').agg({'edad': ['min','mean','max']})

       edad
        min       mean  max
sexo
HOMBRE    0  42.388726  120
MUJER     0  41.450503  120

In [35]:
# varias columnas, una m√©trica
data.groupby('sexo').agg({'edad': 'mean', 'mes_ingreso': 'mean', 'mes_def': 'mean'})

             edad  mes_ingreso   mes_def
sexo
HOMBRE  42.388726     7.056022  6.746797
MUJER   41.450503     7.143418  6.832873

In [36]:
# varias columnas, varias m√©tricas
data.groupby('sexo').agg({'edad': ['min','mean','max'], 'mes_ingreso': ['min','mean','max'], 'mes_def': ['min','mean','max']})

       edad                 mes_ingreso               mes_def
        min       mean  max         min      mean max     min      mean   max
sexo
HOMBRE    0  42.388726  120           1  7.056022  10     1.0  6.746797  10.0
MUJER     0  41.450503  120           1  7.143418  10     1.0  6.832873  10.0

###Descripci√≥n por Tipo

In [37]:
# Filtrar por tipos generales (categ√≥ricas y num√©ricas)
numerical = data.select_dtypes(include='number')
categorical = data.select_dtypes(include=['object', 'bool', 'category', 'datetime64[ns]'])

In [38]:
numerical.head()

   edad  mes_def  a√±o_def  mes_ingreso  a√±o_ingreso
0    38      NaN      NaN            4         2020
1    56      NaN      NaN            4         2020
2    47      NaN      NaN            5         2020
3    43      NaN      NaN            5         2020
4    63      NaN      NaN            5         2020

In [39]:
categorical.head()

  fecha_actualizacion id_registro  ...            resultado defuncion
0          2020-10-05      1c4b18  ...  Positivo SARS-CoV-2     False
1          2020-10-05      081838  ...  Positivo SARS-CoV-2     False
2          2020-10-05      0fefb1  ...  Positivo SARS-CoV-2     False
3          2020-10-05      11ed05  ...  Positivo SARS-CoV-2     False
4          2020-10-05      0ef3ff  ...  Positivo SARS-CoV-2     False

[5 rows x 35 columns]

In [41]:
# para conocer todos los tipo de datos
?data.select_dtypes

####Categ√≥ricas

In [42]:
# Cardinalidad - Valores √∫nicos por columna
for col in categorical.columns:
  print('Valores √∫nicos en "{}": {}'.format(col,categorical[col].nunique()))

Valores √∫nicos en "fecha_actualizacion": 1
Valores √∫nicos en "id_registro": 1758582
Valores √∫nicos en "fecha_ingreso": 279
Valores √∫nicos en "fecha_sintomas": 279
Valores √∫nicos en "fecha_def": 224
Valores √∫nicos en "pais_nacionalidad": 122
Valores √∫nicos en "pais_origen": 81
Valores √∫nicos en "entidad_res": 32
Valores √∫nicos en "municipio_res": 2185
Valores √∫nicos en "entidad_um": 32
Valores √∫nicos en "entidad_nac": 33
Valores √∫nicos en "intubado": 4
Valores √∫nicos en "neumonia": 3
Valores √∫nicos en "embarazo": 4
Valores √∫nicos en "habla_lengua_indig": 3
Valores √∫nicos en "diabetes": 3
Valores √∫nicos en "epoc": 3
Valores √∫nicos en "asma": 3
Valores √∫nicos en "inmusupr": 3
Valores √∫nicos en "hipertension": 3
Valores √∫nicos en "otra_com": 3
Valores √∫nicos en "cardiovascular": 3
Valores √∫nicos en "obesidad": 3
Valores √∫nicos en "renal_cronica": 3
Valores √∫nicos en "tabaquismo": 3
Valores √∫nicos en "otro_caso": 3
Valores √∫nicos en "migrante": 3
Valores √∫nicos en "uci": 4
Valores √∫nicos en "origen": 2
Valores √∫nicos en "sector": 14
Valores √∫nicos en "sexo": 2
Valores √∫nicos en "tipo_paciente": 2
Valores √∫nicos en "nacionalidad": 2
Valores √∫nicos en "resultado": 3
Valores √∫nicos en "defuncion": 2

In [43]:
# Unicidad - proporci√≥n de valores √∫nicos por columna
total = data.shape[0]
for col in categorical.columns:
  print('Porcentaje de valores √∫nicos en "{}": {}%'.format(col,round(categorical[col].nunique()/total*100,2)))

Porcentaje de valores √∫nicos en "fecha_actualizacion": 0.0%
Porcentaje de valores √∫nicos en "id_registro": 100.0%
Porcentaje de valores √∫nicos en "fecha_ingreso": 0.02%
Porcentaje de valores √∫nicos en "fecha_sintomas": 0.02%
Porcentaje de valores √∫nicos en "fecha_def": 0.01%
Porcentaje de valores √∫nicos en "pais_nacionalidad": 0.01%
Porcentaje de valores √∫nicos en "pais_origen": 0.0%
Porcentaje de valores √∫nicos en "entidad_res": 0.0%
Porcentaje de valores √∫nicos en "municipio_res": 0.12%
Porcentaje de valores √∫nicos en "entidad_um": 0.0%
Porcentaje de valores √∫nicos en "entidad_nac": 0.0%
Porcentaje de valores √∫nicos en "intubado": 0.0%
Porcentaje de valores √∫nicos en "neumonia": 0.0%
Porcentaje de valores √∫nicos en "embarazo": 0.0%
Porcentaje de valores √∫nicos en "habla_lengua_indig": 0.0%
Porcentaje de valores √∫nicos en "diabetes": 0.0%
Porcentaje de valores √∫nicos en "epoc": 0.0%
Porcentaje de valores √∫nicos en "asma": 0.0%
Porcentaje de valores √∫nicos en "inmusupr": 0.0%
Porcentaje de valores √∫nicos en "hipertension": 0.0%
Porcentaje de valores √∫nicos en "otra_com": 0.0%
Porcentaje de valores √∫nicos en "cardiovascular": 0.0%
Porcentaje de valores √∫nicos en "obesidad": 0.0%
Porcentaje de valores √∫nicos en "renal_cronica": 0.0%
Porcentaje de valores √∫nicos en "tabaquismo": 0.0%
Porcentaje de valores √∫nicos en "otro_caso": 0.0%
Porcentaje de valores √∫nicos en "migrante": 0.0%
Porcentaje de valores √∫nicos en "uci": 0.0%
Porcentaje de valores √∫nicos en "origen": 0.0%
Porcentaje de valores √∫nicos en "sector": 0.0%
Porcentaje de valores √∫nicos en "sexo": 0.0%
Porcentaje de valores √∫nicos en "tipo_paciente": 0.0%
Porcentaje de valores √∫nicos en "nacionalidad": 0.0%
Porcentaje de valores √∫nicos en "resultado": 0.0%
Porcentaje de valores √∫nicos en "defuncion": 0.0%

In [44]:
# Moda - valor que m√°s se repite en cada columna excepto los indicadores √∫nicos
for col in categorical.drop(columns='id_registro').columns:
  print('Valor m√°s popular en "{}": {}'.format(col, statistics.mode(categorical[col])))

Valor m√°s popular en "fecha_actualizacion": 2020-10-05 00:00:00
Valor m√°s popular en "fecha_ingreso": 2020-07-20 00:00:00
Valor m√°s popular en "fecha_sintomas": 2020-07-20 00:00:00
Valor m√°s popular en "fecha_def": NaT
Valor m√°s popular en "pais_nacionalidad": M√É¬©xico
Valor m√°s popular en "pais_origen": 99
Valor m√°s popular en "entidad_res": CIUDAD DE M√âXICO
Valor m√°s popular en "municipio_res": IZTAPALAPA
Valor m√°s popular en "entidad_um": CIUDAD DE M√âXICO
Valor m√°s popular en "entidad_nac": CIUDAD DE M√âXICO
Valor m√°s popular en "intubado": NO APLICA
Valor m√°s popular en "neumonia": NO
Valor m√°s popular en "embarazo": NO
Valor m√°s popular en "habla_lengua_indig": NO
Valor m√°s popular en "diabetes": NO
Valor m√°s popular en "epoc": NO
Valor m√°s popular en "asma": NO
Valor m√°s popular en "inmusupr": NO
Valor m√°s popular en "hipertension": NO
Valor m√°s popular en "otra_com": NO
Valor m√°s popular en "cardiovascular": NO
Valor m√°s popular en "obesidad": NO
Valor m√°s popular en "renal_cronica": NO
Valor m√°s popular en "tabaquismo": NO
Valor m√°s popular en "otro_caso": SI
Valor m√°s popular en "migrante": NO ESPECIFICADO
Valor m√°s popular en "uci": NO APLICA
Valor m√°s popular en "origen": FUERA DE USMER
Valor m√°s popular en "sector": SSA
Valor m√°s popular en "sexo": MUJER
Valor m√°s popular en "tipo_paciente": AMBULATORIO
Valor m√°s popular en "nacionalidad": MEXICANA
Valor m√°s popular en "resultado": No positivo SARS-CoV-2
Valor m√°s popular en "defuncion": False

####Num√©ricas

In [45]:
numerical.describe()

               edad        mes_def   a√±o_def   mes_ingreso  a√±o_ingreso
count  1.758582e+06  101593.000000  101593.0  1.758582e+06    1758582.0
mean   4.190893e+01       6.778380    2020.0  7.100715e+00       2020.0
std    1.685800e+01       1.446684       0.0  1.536859e+00          0.0
min    0.000000e+00       1.000000    2020.0  1.000000e+00       2020.0
25%    3.000000e+01       6.000000    2020.0  6.000000e+00       2020.0
50%    4.000000e+01       7.000000    2020.0  7.000000e+00       2020.0
75%    5.300000e+01       8.000000    2020.0  8.000000e+00       2020.0
max    1.200000e+02      10.000000    2020.0  1.000000e+01       2020.0

##An√°lisis Exploratorio

En esta secci√≥n responderemos algunas preguntas sobre el set de datos usando las herramientas que hemos visto hasta ahora

In [46]:
# ¬øCu√°ntas pruebas por origen se realizan?
data.groupby('origen').id_registro.count()

origen
FUERA DE USMER    1184574
USMER              574008
Name: id_registro, dtype: int64

In [47]:
data.origen.value_counts()

FUERA DE USMER    1184574
USMER              574008
Name: origen, dtype: int64

In [48]:
# ¬øCu√°ntas pruebas por sector se realizan?
data.sector.value_counts()

SSA                1102218
IMSS                450200
ISSSTE               65651
PRIVADA              63312
ESTATAL              30190
PEMEX                14376
IMSS-BIENESTAR       11286
SEDENA                8760
SEMAR                 8603
MUNICIPAL             1457
UNIVERSITARIO         1330
DIF                    943
CRUZ ROJA              246
NO ESPECIFICADO         10
Name: sector, dtype: int64

In [49]:
# ¬øCu√°ntos pacientes por sexo tenemos?
data.sexo.value_counts()

MUJER     899323
HOMBRE    859259
Name: sexo, dtype: int64

In [50]:
# ¬øCu√°l es la proporci√≥n de los pacientes por sexo?
data.sexo.value_counts(normalize=True)

MUJER     0.511391
HOMBRE    0.488609
Name: sexo, dtype: float64

In [51]:
# ¬øCu√°l es la proporci√≥n de resultados de las pruebas?
data.resultado.value_counts(normalize=True)

No positivo SARS-CoV-2    0.519256
Positivo SARS-CoV-2       0.435056
Resultado pendiente       0.045687
Name: resultado, dtype: float64

In [52]:
# ¬øCu√°ntas pruebas positivas tenemos en el set?
data[data.resultado == 'Positivo SARS-CoV-2'].id_registro.count()

765082

In [53]:
# ¬øCu√°ntos casos positivos tenemos por mes?
data[data.resultado == 'Positivo SARS-CoV-2'].mes_ingreso.value_counts().sort_index()

1          2
2          8
3       2538
4      26639
5      86928
6     153396
7     200504
8     158212
9     131675
10      5180
Name: mes_ingreso, dtype: int64

In [54]:
# ¬øCu√°l es el resultado de las pruebas por sexo?
data.groupby(['sexo','resultado'])['id_registro'].count()

sexo    resultado
HOMBRE  No positivo SARS-CoV-2    423206
        Positivo SARS-CoV-2       396242
        Resultado pendiente        39811
MUJER   No positivo SARS-CoV-2    489949
        Positivo SARS-CoV-2       368840
        Resultado pendiente        40534
Name: id_registro, dtype: int64

In [55]:
data.groupby('sexo').resultado.value_counts()

sexo    resultado
HOMBRE  No positivo SARS-CoV-2    423206
        Positivo SARS-CoV-2       396242
        Resultado pendiente        39811
MUJER   No positivo SARS-CoV-2    489949
        Positivo SARS-CoV-2       368840
        Resultado pendiente        40534
Name: resultado, dtype: int64

In [56]:
# ¬øQu√© proporci√≥n de resultados de pruebas tenemos por sexo?
data.groupby('sexo').resultado.value_counts(normalize=True)

sexo    resultado
HOMBRE  No positivo SARS-CoV-2    0.492524
        Positivo SARS-CoV-2       0.461144
        Resultado pendiente       0.046332
MUJER   No positivo SARS-CoV-2    0.544798
        Positivo SARS-CoV-2       0.410131
        Resultado pendiente       0.045072
Name: resultado, dtype: float64

In [57]:
# ¬øCu√°l es la edad de los pacientes por sexo?
data.groupby('sexo').edad.describe()

           count       mean        std  min   25%   50%   75%    max
sexo
HOMBRE  859259.0  42.388726  17.192459  0.0  30.0  41.0  54.0  120.0
MUJER   899323.0  41.450503  16.519120  0.0  29.0  40.0  52.0  120.0

In [58]:
def q25(x):
  return x.quantile(0.25)

def q75(x):
  return x.quantile(0.75)

data.groupby('sexo').agg({'edad': ['min', q25, 'median', q75, 'max']})

       edad
        min q25 median q75  max
sexo
HOMBRE    0  30     41  54  120
MUJER     0  29     40  52  120

In [59]:
# ¬øCu√°l es la edad de los pacientes dependiendo de si son intubados o no?
data.groupby('intubado').edad.describe()

                     count       mean        std  min   25%   50%   75%    max
intubado
NO                248792.0  53.377793  19.836354  0.0  42.0  55.0  68.0  118.0
NO APLICA        1467235.0  39.527140  15.161776  0.0  29.0  38.0  49.0  120.0
NO ESPECIFICADO      199.0  54.648241  17.662861  0.0  44.0  57.0  67.0   92.0
SI                 42356.0  56.989305  18.062616  0.0  48.0  59.0  69.0  109.0

In [60]:
data.groupby('intubado').agg({'edad': ['min', q25, 'median', q75, 'max']})

                edad
                 min q25 median q75  max
intubado
NO                 0  42     55  68  118
NO APLICA          0  29     38  49  120
NO ESPECIFICADO    0  44     57  67   92
SI                 0  48     59  69  109

In [61]:
# ¬øCu√°l es la edad m√°xima y cu√°l es la m√≠nima de los pacientes fallecidos?
edad_def_max = data[data.defuncion].edad.max()
data[data.defuncion & (data.edad == edad_def_max)]

       fecha_actualizacion id_registro  ... mes_ingreso a√±o_ingreso
595521          2020-10-05      1b7b20  ...           5        2020

[1 rows x 40 columns]

In [62]:
edad_def_min = data[data.defuncion].edad.min()
data[data.defuncion & (data.edad == edad_def_min)]

        fecha_actualizacion id_registro  ... mes_ingreso a√±o_ingreso
9277             2020-10-05      02f8e2  ...           5        2020
12174            2020-10-05      083c34  ...           5        2020
21651            2020-10-05      1b82ee  ...           5        2020
37736            2020-10-05      053398  ...           6        2020
41919            2020-10-05      014b5d  ...           5        2020
...                     ...         ...  ...         ...         ...
1680860          2020-10-05      1d807b  ...           8        2020
1713642          2020-10-05      1e94e4  ...           8        2020
1722238          2020-10-05      00f39c  ...           7        2020
1726202          2020-10-05      320231  ...          10        2020
1751411          2020-10-05      3b8095  ...           9        2020

[287 rows x 40 columns]

In [63]:
# ¬øCu√°l es la edad de los pacientes que fallecen?
data.groupby('defuncion').edad.describe()

               count       mean        std  min   25%   50%   75%    max
defuncion
False      1656989.0  40.672703  16.154277  0.0  29.0  39.0  51.0  120.0
True        101593.0  62.071826  15.219535  0.0  53.0  63.0  73.0  109.0

In [64]:
# ¬øCu√°ntas defunciones tenemos por mes?
data[data.defuncion].mes_def.value_counts().sort_index()

1.0         6
2.0        12
3.0       232
4.0      5301
5.0     16162
6.0     21663
7.0     24557
8.0     19664
9.0     13253
10.0      743
Name: mes_def, dtype: int64

In [65]:
# ¬øCu√°l es la proporci√≥n de di√°beticos para las defunciones?
data.groupby('diabetes').defuncion.value_counts(normalize=True)

diabetes   defuncion
NO         False        0.959752
           True         0.040248
SE IGNORA  False        0.881769
           True         0.118231
SI         False        0.814988
           True         0.185012
Name: defuncion, dtype: float64

In [66]:
# ¬øCu√°l es la proporci√≥n de asm√°ticos para las defunciones?
data.groupby('asma').defuncion.value_counts(normalize=True)

asma       defuncion
NO         False        0.941919
           True         0.058081
SE IGNORA  False        0.879195
           True         0.120805
SI         False        0.958975
           True         0.041025
Name: defuncion, dtype: float64

In [67]:
# ¬øCu√°l es la proporci√≥n de hipertensos para las defunciones?
data.groupby('hipertension').defuncion.value_counts(normalize=True)

hipertension  defuncion
NO            False        0.962312
              True         0.037688
SE IGNORA     False        0.881891
              True         0.118109
SI            False        0.836635
              True         0.163365
Name: defuncion, dtype: float64

In [74]:
# ¬øCuantos positivos tenemos por estado?
data[data.resultado == 'Positivo SARS-CoV-2'].entidad_res.value_counts()

CIUDAD DE M√âXICO                   130964
M√âXICO                              82804
GUANAJUATO                          41955
NUEVO LE√ìN                          41843
VERACRUZ DE IGNACIO DE LA LLAVE     33972
TABASCO                             32246
PUEBLA                              31706
TAMAULIPAS                          29437
JALISCO                             28128
COAHUILA DE ZARAGOZA                27331
SONORA                              25004
SAN LUIS POTOS√ç                     23717
MICHOAC√ÅN DE OCAMPO                 21378
BAJA CALIFORNIA                     19824
GUERRERO                            19709
SINALOA                             19122
YUCAT√ÅN                             18811
OAXACA                              17513
HIDALGO                             13094
QUINTANA ROO                        12156
CHIHUAHUA                           11785
BAJA CALIFORNIA SUR                 10655
QUER√âTARO                            9558
DURANGO                              9467
ZACATECAS                            7777
TLAXCALA                             7611
AGUASCALIENTES                       7545
CHIAPAS                              6579
NAYARIT                              6127
CAMPECHE                             6027
MORELOS                              6019
COLIMA                               5218
Name: entidad_res, dtype: int64

In [76]:
# ¬øCu√°ntas defunciones tenemos por estado?
data[data.defuncion].entidad_res.value_counts()

M√âXICO                             15152
CIUDAD DE M√âXICO                   13241
VERACRUZ DE IGNACIO DE LA LLAVE     5398
PUEBLA                              5062
JALISCO                             4680
BAJA CALIFORNIA                     4407
NUEVO LE√ìN                          4240
SINALOA                             4148
GUANAJUATO                          3698
TAMAULIPAS                          3497
SONORA                              3482
TABASCO                             3117
COAHUILA DE ZARAGOZA                2604
GUERRERO                            2518
HIDALGO                             2411
MICHOAC√ÅN DE OCAMPO                 2325
CHIHUAHUA                           2306
SAN LUIS POTOS√ç                     2180
QUINTANA ROO                        2120
YUCAT√ÅN                             2068
OAXACA                              1778
TLAXCALA                            1414
MORELOS                             1366
CHIAPAS                             1251
QUER√âTARO                           1176
CAMPECHE                            1024
ZACATECAS                            954
NAYARIT                              947
DURANGO                              873
AGUASCALIENTES                       800
COLIMA                               725
BAJA CALIFORNIA SUR                  631
Name: entidad_res, dtype: int64

In [78]:
# ¬øCu√°ntas defunciones tenemos por tipo de paciente?
data[data.defuncion].tipo_paciente.value_counts()

HOSPITALIZADO    90918
AMBULATORIO      10675
Name: tipo_paciente, dtype: int64